services:
  angular_app:
    container_name: angular_app
    image: angular_app:1.0.0
    build: ./angular/prueba-tecnica-app/
    ports:
      - "4200:4200"
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: java-app:1.0.0
    build: .
    ports:
      - "8090:8090"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres